### PR TITLE
Add a marvel music player project

### PR DESCRIPTION
**Pull request by purnasth**
# Pull Request: Feature Addition - Marvel Music Player

## Description
This pull request adds the Marvel Music Player, a new project to the repository. 

## Changes Made
- Added the Marvel Music Player to the repo.
- Add project and contributor details to the contributors.md

## Attachments 
image

## Additional Details
I'm excited to contribute this new project to the repository and look forward to feedback and suggestions for further improvements. Thank you for considering this addition.

### CODE REVIEW

**Comment by Manishak798** [comment]
Kindly resolve the merge conflicts.

**Comment by purnasth** [comment]
Since I'm new to the open-source community, could you kindly explain what the conflicts in this case are?

**Comment by Manishak798** [comment]
Sure, on github in your commits files you can see some errors highlighting in red color 
that you need to remove.

> Since I'm new to the open-source community, could you kindly explain what the conflicts in this case are?

**Comment by purnasth** [comment]
I had formatted the code with the prettier. Is this conflict because of that ?

**Comment by Manishak798** [comment]
No, I am not talking about the code formatting. You need to remove the merge conflicts highlighted in the red color.

> I had formatted the code with the prettier. Is this conflict because of that ?

**Comment by purnasth** [comment]
Sorry, for creating a merge conflict again. Is it because I pushed it into this PR before syncing the repo with and forked the repo and without pulling the codes from the main branch?

**Pull request closed without merging**
